version: "3.9"
services:
  app:
    build:
      args:
        user: ${USER}
        uid: ${UID}
      context: ./docker
      dockerfile: Dockerfile
    image: confia-admin
    container_name: confia-admin
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
  nginx:
    image: nginx:1.19-alpine
    container_name: confia-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
networks:
  default:
    external:
      name: confia
