version: "3.9"
services:
  app:
    build:
      args:
        user: ${USER}
        uid: ${UID}
      context: ./docker
      dockerfile: Dockerfile
    image: confia-admin
    container_name: confia-admin
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - confianet
  db:
    image: postgres
    container_name: confia-admin-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5433:5432
    volumes:
      - confia-db-data:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d
    networks:
      - confianet
  nginx:
    image: nginx:1.19-alpine
    container_name: confia-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - confianet
volumes:
  confia-db-data:
networks:
  confianet:
    driver: bridge
